force-app/main/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Campo para armazenar o Codigo Calculado automaticamente pelos Recursos atribuidos a este produto</description>
    <externalId>true</externalId>
    <inlineHelpText>Campo para armazenar o Codigo Calculado automaticamente pelos Recursos atribuidos a este produto</inlineHelpText>
    <label>Codigo Interno (CPQ)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TipoRecursoProduto__c/TipoRecursoProduto__c.object-meta.xml
<CustomObject>
    <label>Tipo Recurso do Produto</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>Recurso</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tipos de Recurso do Produto</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TipoRecursoProduto__c/fields/ChaveInternaDuplicidade__c.field-meta.xml
<CustomField>
    <fullName>ChaveInternaDuplicidade__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Chave Interna para Duplicidade</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/TipoRecursoProduto__c/fields/IdentificadorBase__c.field-meta.xml
<CustomField>
    <fullName>IdentificadorBase__c</fullName>
    <formula>Produto__r.EstruturaProduto__r.CodigoInterno__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Identificador Base</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TipoRecursoProduto__c/fields/IdentificadorChave__c.field-meta.xml
<CustomField>
    <fullName>IdentificadorChave__c</fullName>
    <formula>TipoRecurso__r.Sequencial__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Identificador Chave</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TipoRecursoProduto__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Tipos de Recursos do  Produto</relationshipLabel>
    <relationshipName>TiposRecursosProduto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TipoRecursoProduto__c/fields/Sequencial__c.field-meta.xml
<CustomField>
    <fullName>Sequencial__c</fullName>
    <formula>TipoRecurso__r.RecursoProduto__r.Sequencial__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sequencial</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TipoRecursosProdutoHelper.cls
public class TipoRecursosProdutoHelper {
    private static Boolean runTrigger;
    static {
        runTrigger = true;
    }

    public static Boolean isTriggerEnabled(){
        return runTrigger;
    }

    public static Boolean enableTrigger(){
        return runTrigger = true;
    }

    public static Boolean disableTrigger(){
        return runTrigger = false;
    }

    public static void updateInternalId(TipoRecursoProduto__c[] context){
        for(TipoRecursoProduto__c record : context){
            record.ChaveInternaDuplicidade__c = record.Produto__c +' - '+record.Sequencial__c; 
        }
    }
    public static void updateExternalIdProduct(TipoRecursoProduto__c[] context){
        Map<Id, Map<Decimal, String>> contextMap = new Map<Id, Map<Decimal, String>>();
        Map<Id, String> prodIdMap = new Map<Id, String>();
        for(TipoRecursoProduto__c record : context){
            if(!contextMap.containsKey(record.Produto__c))
                contextMap.put(record.Produto__c, new Map<Decimal, String>());
            contextMap.get(record.Produto__c).put(0, record.IdentificadorBase__c);
        }

        for(TipoRecursoProduto__c record : [SELECT id, Sequencial__c, IdentificadorChave__c, Produto__c
                                            FROM TipoRecursoProduto__c 
                                            WHERE Produto__c IN :contextMap.keySet() 
                                            ORDER BY Produto__c DESC, Sequencial__c ASC]){
            contextMap.get(record.Produto__c).put(record.Sequencial__c, record.IdentificadorChave__c);
        }

        List<Product2> productList= new List<Product2>();
        for(Id prodId : contextMap.keySet()){
            productList.add(new Product2(Id = prodId, ExternalId__c = String.join(contextMap.get(prodId).values(), '')));
        }

        if(!productList.isEmpty()){
            update productList;
        }
    }
}