force-app/main/default/objects/EstruturaProduto__c/EstruturaProduto__c.object-meta.xml
<CustomObject>
    <label>Estrutura de Produto</label>
    <nameField>
        <label>Estrutura de Produto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estrutura de Produto</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2/fields/EstruturaProduto__c.field-meta.xml
<CustomField>
    <fullName>EstruturaProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estrutura de Produto</label>
    <referenceTo>EstruturaProduto__c</referenceTo>
    <relationshipLabel>Produtos</relationshipLabel>
    <relationshipName>Produtos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Campo para armazenar o Codigo Calculado automaticamente pelos Recursos atribuidos a este produto</description>
    <externalId>true</externalId>
    <inlineHelpText>Campo para armazenar o Codigo Calculado automaticamente pelos Recursos atribuidos a este produto</inlineHelpText>
    <label>Codigo Interno (CPQ)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductCodeExternalId__c.field-meta.xml
<CustomField>
    <fullName>ProductCodeExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Código do produto (Id Externo)</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/TipoRecursoProduto__c/TipoRecursoProduto__c.object-meta.xml
<CustomObject>
    <label>Tipo Recurso do Produto</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>Recurso</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tipos de Recurso do Produto</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TipoRecursoProduto__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Tipos de Recursos do  Produto</relationshipLabel>
    <relationshipName>TiposRecursosProduto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TipoRecursoProduto__c/fields/TipoRecurso__c.field-meta.xml
<CustomField>
    <fullName>TipoRecurso__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tipo de Recursos do Produto</label>
    <referenceTo>TiposRecurso__c</referenceTo>
    <relationshipLabel>Produtos</relationshipLabel>
    <relationshipName>Produtos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TipoRecursosProduto__c/TipoRecursosProduto__c.object-meta.xml
<CustomObject>
    <label>Tipo de Recursos do Produto</label>
    <nameField>
        <displayFormat>TP-{0000}</displayFormat>
        <label>Nome</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tipo de Recursos dos Produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TipoRecursosProduto__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Tipo de Recursos dos Produtos</relationshipLabel>
    <relationshipName>TipoRecurso</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TipoRecursosProduto__c/fields/TipoRecurso__c.field-meta.xml
<CustomField>
    <fullName>TipoRecurso__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tipos de Recurso</label>
    <referenceTo>TiposRecurso__c</referenceTo>
    <relationshipLabel>Tipo de Recursos dos Produtos</relationshipLabel>
    <relationshipName>TipoRecursoProduto</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TiposRecurso__c/TiposRecurso__c.object-meta.xml
<CustomObject>
    <label>Tipos de Recurso</label>
    <nameField>
        <displayFormat>TR-{00000}</displayFormat>
        <label>Tipos de Recurso</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tipos de Recurso</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TiposRecurso__c/fields/EstruturaProduto__c.field-meta.xml
<CustomField>
    <fullName>EstruturaProduto__c</fullName>
    <formula>RecursoProduto__r.EstruturaProduto__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Estrutura do produto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CreateStructureResourcesController.cls
public class CreateStructureResourcesController {

    public String booking {get;set;}

    public CreateStructureResourcesController() 	{}
	@RemoteAction
	public static ProductListData getCurrentRecordsSteris(List<ProductResourceData> excelDataList){
		Set<String> structureSet = new Set<String>();
		Set<String> productSet = new Set<String>();
		Set<String> internalSet = new Set<String>();

		for(ProductResourceData record: excelDataList){
			structureSet.add(record.structureName);
			productSet.add(record.productCode);
			internalSet.add(record.internalKey);
		}

        List<String> structureList = new List<String>();
        for(EstruturaProduto__c record : [SELECT Name FROM EstruturaProduto__c WHERE Ativo__c = true AND NAME IN :structureSet]){
            structureList.add(record.Name);
        }

        
        List<String> productList = new List<String>();
        for(Product2 record : [SELECT ProductCodeExternalId__c FROM Product2 WHERE isActive = true AND ProductCodeExternalId__c != null AND ProductCodeExternalId__c IN :productSet]){
            productList.add(record.ProductCodeExternalId__c);
        }

        
        List<String> internalList = new List<String>();
        for(TiposRecurso__c record : [SELECT ExternalId__c FROM TiposRecurso__c WHERE Ativo__c = true AND ExternalId__c IN :internalSet]){
            internalList.add(record.ExternalId__c.replaceAll('[^a-zA-Z0-9]', ''));
        }
		return new ProductListData(structureList, productList, internalList);
	}

	@RemoteAction
	public static String createRecords(String entryList){
		List<ProductResourceData> excelDataList = (List<ProductResourceData>)JSON.deserialize(entryList, List<ProductResourceData>.class);
		
        System.debug('excelDataList => ' + excelDataList);

		Map<String, SObject> lookups = new Map<String, SObject>();

		for (ProductResourceData oppData : excelDataList){
			lookups.put(oppData.structureName, null);
			lookups.put(oppData.productCode, null);
			lookups.put(oppData.internalKey, null);
        }

		for (EstruturaProduto__c record : [SELECT Id, Name FROM EstruturaProduto__c WHERE Ativo__c = true AND Name IN: lookups.keySet()]){
			lookups.put(record.Name, record);
		}
		for (Product2 record : [SELECT Id, ProductCodeExternalId__c FROM Product2 WHERE ProductCodeExternalId__c  IN: lookups.keySet()]){
			lookups.put(record.ProductCodeExternalId__c, record);
		}
		for (TipoRecursoProduto__c record : [SELECT Id, TipoRecurso__r.ExternalId__c, Produto__r.ProductCodeExternalId__c FROM TipoRecursoProduto__c WHERE Produto__r.ProductCodeExternalId__c  IN: lookups.keySet() AND TipoRecurso__r.ExternalId__c IN: lookups.keySet() ]){
			lookups.put(record.TipoRecurso__r.ExternalId__c +'-'+ record.Produto__r.ProductCodeExternalId__c, record);
		}

		Map<String, TipoRecursoProduto__c> productResouceMap = new Map<String, TipoRecursoProduto__c>();
		Map<String, TipoRecursoProduto__c> productResouceUpdateMap = new Map<String, TipoRecursoProduto__c>();
		Map<String, Product2> productMap = new Map<String, Product2>();
		for (ProductResourceData resourceData : excelDataList){
			TipoRecursoProduto__c resourceType = resourceData.getProductResourceData(lookups);
			String key = resourceData.internalKey +'-'+resourceData.productCode;
			System.debug(resourceType);
			if(!lookups.containsKey(key)){
            	productResouceMap.put(key, resourceType);
			}else{
				resourceType.Id = (Id)lookups.get(key).get('Id');
            	productResouceUpdateMap.put(key, resourceType);
			}
            productMap.put(resourceData.productCode, resourceData.getProduct(lookups));
		}

		System.debug('\nproductResouceMap => ' + productResouceMap);
		System.debug('\nproductMap => ' + productMap);

		String response = 'Sucesso';
		if (!productResouceMap.isEmpty()){
			Database.insert(productResouceMap.values(), false);
		}

		if (!productResouceUpdateMap.isEmpty()){
			Database.update(productResouceUpdateMap.values(), false);
		}

		if (!productMap.isEmpty()){
			Database.update(productMap.values());
		}

		return response;
	}

	public class ProductListData{
		public List<String> structureList {get; set;}
		public List<String> productList {get; set;}
		public List<String> internalList {get; set;}
		public ProductListData(List<String> structureList, List<String> productList, List<String> internalList){
			this.structureList = structureList;
			this.productList = productList;
			this.internalList = internalList;
		}
	}
	public class ProductResourceData{
		public String structureName {get; set;}
		public String productCode {get; set;}
		public String internalKey {get; set;}
		public Boolean isInvalid {get; set;}
		public Integer internalId {get; set;}
		public String errorMessage {get; set;}

		public ProductResourceData(Boolean isTest){
			if (isTest){
				this.structureName = 'CAM-0190';
				this.productCode = '100231';
				this.internalKey = '1002';
				this.isInvalid = true;
				this.internalId = 1;
				this.errorMessage = '';
			}
		}

		public Product2 getProduct(Map<String, sObject> lookups){
			return new Product2(
                Id = lookups.get(this.productCode) != null ? (Id)lookups.get(this.productCode).get('Id') : null,
                EstruturaProduto__c = lookups.get(this.structureName) != null ? (Id)lookups.get(this.structureName).get('Id') : null
			);
		}
		public TipoRecursoProduto__c getProductResourceData(Map<String, sObject> lookups){
			return new TipoRecursoProduto__c(
                Produto__r = new Product2(ProductCodeExternalId__c = this.productCode),
                TipoRecurso__r = new TiposRecurso__c(ExternalId__c = this.internalKey)
			);
		}
	}
}