force-app/main/default/objects/EstruturaProduto__c/EstruturaProduto__c.object-meta.xml
<CustomObject>
    <label>Estrutura de Produto</label>
    <nameField>
        <label>Estrutura de Produto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estrutura de Produto</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EstruturaProduto__c/fields/Agrupador__c.field-meta.xml
<CustomField>
    <fullName>Agrupador__c</fullName>
    <label>Agrupador</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ferramenta de Automação</fullName>
            </value>
            <value>
                <fullName>Foco XLED</fullName>
            </value>
            <value>
                <fullName>Esterilizadora</fullName>
                <isActive>false</isActive>
                <label>Esterilizadora</label>
            </value>
            <value>
                <fullName>Lavadora</fullName>
                <isActive>false</isActive>
                <label>Lavadora</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EstruturaProduto__c/fields/CodigoInterno__c.field-meta.xml
<CustomField>
    <fullName>CodigoInterno__c</fullName>
    <externalId>true</externalId>
    <label>Codigo Interno</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KitAcessorios__c/KitAcessorios__c.object-meta.xml
<CustomObject>
    <label>Kit de Acessórios</label>
    <nameField>
        <label>Nome do Kit de Acessórios</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Kit de Acessórios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KitAcessorios__c/fields/CodigoInterno__c.field-meta.xml
<CustomField>
    <fullName>CodigoInterno__c</fullName>
    <externalId>true</externalId>
    <label>Código Interno</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/KitAcessorios__c/fields/PossuiObrigatorios__c.field-meta.xml
<CustomField>
    <fullName>PossuiObrigatorios__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Possui Obrigatórios</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/ParentProduct__c.field-meta.xml
<CustomField>
    <fullName>ParentProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto do kit</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Itens da linha de cotação</relationshipLabel>
    <relationshipName>ParentProductsOpportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/EstruturaProduto__c.field-meta.xml
<CustomField>
    <fullName>EstruturaProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estrutura de Produto</label>
    <referenceTo>EstruturaProduto__c</referenceTo>
    <relationshipLabel>Produtos</relationshipLabel>
    <relationshipName>Produtos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Campo para armazenar o Codigo Calculado automaticamente pelos Recursos atribuidos a este produto</description>
    <externalId>true</externalId>
    <inlineHelpText>Campo para armazenar o Codigo Calculado automaticamente pelos Recursos atribuidos a este produto</inlineHelpText>
    <label>Codigo Interno (CPQ)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Imagem_URL__c.field-meta.xml
<CustomField>
    <fullName>Imagem_URL__c</fullName>
    <defaultValue>&quot;https://c.na30.content.force.com/servlet/servlet.ImageServer?id=01536000002SKID&amp;oid=00D36000000Yc59&amp;lastMod=1479819637000&quot;</defaultValue>
    <label>Imagem URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/KitAcessorios__c.field-meta.xml
<CustomField>
    <fullName>KitAcessorios__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Kit de Acessórios</label>
    <referenceTo>KitAcessorios__c</referenceTo>
    <relationshipLabel>Produtos</relationshipLabel>
    <relationshipName>Produtos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductCodeExternalId__c.field-meta.xml
<CustomField>
    <fullName>ProductCodeExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Código do produto (Id Externo)</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ParentProduct__c.field-meta.xml
<CustomField>
    <fullName>ParentProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto do kit</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Itens da linha de cotação</relationshipLabel>
    <relationshipName>ParentProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RecursosProduto__c/RecursosProduto__c.object-meta.xml
<CustomObject>
    <label>Recursos do Produto</label>
    <nameField>
        <label>Recursos do Produto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recursos do Produto</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RecursosProduto__c/fields/Agrupador__c.field-meta.xml
<CustomField>
    <fullName>Agrupador__c</fullName>
    <formula>TEXT(EstruturaProduto__r.Agrupador__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Agrupador</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RecursosProduto__c/fields/EstruturaProduto__c.field-meta.xml
<CustomField>
    <fullName>EstruturaProduto__c</fullName>
    <label>Estrutura de Produto</label>
    <referenceTo>EstruturaProduto__c</referenceTo>
    <relationshipLabel>Recursos do Produto</relationshipLabel>
    <relationshipName>RecursosProduto</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RecursosProduto__c/fields/Sequencial__c.field-meta.xml
<CustomField>
    <fullName>Sequencial__c</fullName>
    <label>Sequencial</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TipoRecursoProduto__c/TipoRecursoProduto__c.object-meta.xml
<CustomObject>
    <label>Tipo Recurso do Produto</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>Recurso</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tipos de Recurso do Produto</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TipoRecursoProduto__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Tipos de Recursos do  Produto</relationshipLabel>
    <relationshipName>TiposRecursosProduto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TipoRecursoProduto__c/fields/Sequencial__c.field-meta.xml
<CustomField>
    <fullName>Sequencial__c</fullName>
    <formula>TipoRecurso__r.RecursoProduto__r.Sequencial__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sequencial</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TipoRecursoProduto__c/fields/TipoRecurso__c.field-meta.xml
<CustomField>
    <fullName>TipoRecurso__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tipo de Recursos do Produto</label>
    <referenceTo>TiposRecurso__c</referenceTo>
    <relationshipLabel>Produtos</relationshipLabel>
    <relationshipName>Produtos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TiposRecurso__c/TiposRecurso__c.object-meta.xml
<CustomObject>
    <label>Tipos de Recurso</label>
    <nameField>
        <displayFormat>TR-{00000}</displayFormat>
        <label>Tipos de Recurso</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tipos de Recurso</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TiposRecurso__c/fields/Agrupador__c.field-meta.xml
<CustomField>
    <fullName>Agrupador__c</fullName>
    <formula>TEXT(RecursoProduto__r.EstruturaProduto__r.Agrupador__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Agrupador</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TiposRecurso__c/fields/DescricaoRecurso__c.field-meta.xml
<CustomField>
    <fullName>DescricaoRecurso__c</fullName>
    <label>Descrição do Tipo de Recurso</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TiposRecurso__c/fields/EstruturaProduto__c.field-meta.xml
<CustomField>
    <fullName>EstruturaProduto__c</fullName>
    <formula>RecursoProduto__r.EstruturaProduto__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Estrutura do produto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TiposRecurso__c/fields/RecursoProduto__c.field-meta.xml
<CustomField>
    <fullName>RecursoProduto__c</fullName>
    <label>Recursos do Produto</label>
    <referenceTo>RecursosProduto__c</referenceTo>
    <relationshipLabel>Tipos de Recurso</relationshipLabel>
    <relationshipName>ComposicaoProduto</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TiposRecurso__c/fields/Sequencial__c.field-meta.xml
<CustomField>
    <fullName>Sequencial__c</fullName>
    <label>Sequencial Identificador</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProductScreenControllerTest.cls
@IsTest
private with sharing class ProductScreenControllerTest {
	@TestSetup
	static void makeData() {
		update new Pricebook2(
			Id = Test.getStandardPricebookId(),
			IsActive = true
		);

		Account newAccount = new Account(
			Name = 'Account Test'
		);
		insert newAccount;

		Opportunity newOpportunity = new Opportunity(
			AccountId = newAccount.Id,
			Name = 'Opportunity Test',
			CloseDate = Date.today() + 30,
			StageName = 'Qualification',
			Pricebook2Id = Test.getStandardPricebookId()
		);
		insert newOpportunity;

		Quote newQuote = new Quote(
			Name = 'Quote Test',
			OpportunityId = newOpportunity.Id,
			Pricebook2Id = Test.getStandardPricebookId()
		);
		insert newQuote;

		EstruturaProduto__c newStructure = new EstruturaProduto__c(
			Name = 'Structure Test',
			Agrupador__c = 'Foco XLED',
			CodigoInterno__c = 'Foco XLED',
			Ativo__c = true
		);
		insert newStructure;

		KitAcessorios__c newKit = new KitAcessorios__c(
			Name = 'Kit Test',
			CodigoInterno__c = '01',
			PossuiObrigatorios__c = false,
			Ativo__c = true
		);
		insert newKit;

		List<Product2> newProductList = new List<Product2>{
			new Product2(
				Name = 'Product 1',
				ExternalId__c = '010305',
				EstruturaProduto__c = newStructure.Id,
				IsActive = true
			),
			new Product2(
				Name = 'Product 2',
				ExternalId__c = '020406',
				EstruturaProduto__c = newStructure.Id,
				KitAcessorios__c = newKit.Id,
				IsActive = true
			),
			new Product2(
				Name = 'Product 3',
				ExternalId__c = '020407',
				EstruturaProduto__c = newStructure.Id,
				IsActive = true
			),
			new Product2(
				Name = 'Product 4',
				ExternalId__c = '020408',
				EstruturaProduto__c = newStructure.Id,
				IsActive = true
			)
		};
		insert newProductList;

		List<PricebookEntry> pricebookEntryList = new List<PricebookEntry>{
			new PricebookEntry(
				UnitPrice = 100,
				Pricebook2Id = Test.getStandardPricebookId(),
				Product2Id = newProductList[0].Id,
				IsActive = true
			),
			new PricebookEntry(
				UnitPrice = 100,
				Pricebook2Id = Test.getStandardPricebookId(),
				Product2Id = newProductList[1].Id,
				IsActive = true
			),
			new PricebookEntry(
				UnitPrice = 100,
				Pricebook2Id = Test.getStandardPricebookId(),
				Product2Id = newProductList[2].Id,
				IsActive = true
			),
			new PricebookEntry(
				UnitPrice = 100,
				Pricebook2Id = Test.getStandardPricebookId(),
				Product2Id = newProductList[3].Id,
				IsActive = true
			)
		};
		insert pricebookEntryList;

		insert new List<OpportunityLineItem>{
			new OpportunityLineItem(
				Quantity = 100,
				UnitPrice = 100,
				Product2Id = newProductList[0].Id,
				OpportunityId = newOpportunity.Id
			),
			new OpportunityLineItem(
				Quantity = 100,
				UnitPrice = 100,
				Product2Id = newProductList[1].Id,
				OpportunityId = newOpportunity.Id
			),
			new OpportunityLineItem(
				Quantity = 100,
				UnitPrice = 100,
				ParentProduct__c = newProductList[0].Id,
				Product2Id = newProductList[2].Id,
				OpportunityId = newOpportunity.Id
			),
			new OpportunityLineItem(
				Quantity = 100,
				UnitPrice = 100,
				ParentProduct__c = newProductList[1].Id,
				Product2Id = newProductList[3].Id,
				OpportunityId = newOpportunity.Id
			)
		};

		insert new List<QuoteLineItem>{
			new QuoteLineItem(
				Quantity = 100,
				UnitPrice = 100,
				Product2Id = newProductList[0].Id,
				PricebookEntryId = pricebookEntryList[0].Id,
				QuoteId = newQuote.Id
			),
			new QuoteLineItem(
				Quantity = 100,
				UnitPrice = 100,
				Product2Id = newProductList[1].Id,
				PricebookEntryId = pricebookEntryList[1].Id,
				QuoteId = newQuote.Id
			)
		};

		List<RecursosProduto__c> newResourceList = new List<RecursosProduto__c>{
			new RecursosProduto__c(
				Name = 'Dimension',
				EstruturaProduto__c = newStructure.Id,
				Sequencial__c = 1
			),
			new RecursosProduto__c(
				Name = 'Door Type',
				EstruturaProduto__c = newStructure.Id,
				Sequencial__c = 2
			),
			new RecursosProduto__c(
				Name = 'Mounting',
				EstruturaProduto__c = newStructure.Id,
				Sequencial__c = 3
			)
		};
		insert newResourceList;

		insert new List<TiposRecurso__c>{
			new TiposRecurso__c(
				DescricaoRecurso__c = 'D1',
				Sequencial__c = '1',
				ExternalId__c = '01',
				RecursoProduto__c = newResourceList[0].Id,
				Ativo__c = true
			),
			new TiposRecurso__c(
				DescricaoRecurso__c = 'D2',
				Sequencial__c = '2',
				ExternalId__c = '02',
				RecursoProduto__c = newResourceList[0].Id,
				Ativo__c = true
			),
			new TiposRecurso__c(
				DescricaoRecurso__c = 'DT3',
				Sequencial__c = '3',
				ExternalId__c = '03',
				RecursoProduto__c = newResourceList[1].Id,
				Ativo__c = true
			),
			new TiposRecurso__c(
				DescricaoRecurso__c = 'DT4',
				Sequencial__c = '4',
				ExternalId__c = '04',
				RecursoProduto__c = newResourceList[1].Id,
				Ativo__c = true
			),
			new TiposRecurso__c(
				DescricaoRecurso__c = 'M5',
				Sequencial__c = '5',
				ExternalId__c = '05',
				RecursoProduto__c = newResourceList[2].Id,
				Ativo__c = true
			),
			new TiposRecurso__c(
				DescricaoRecurso__c = 'M6',
				Sequencial__c = '6',
				ExternalId__c = '06',
				RecursoProduto__c = newResourceList[2].Id,
				Ativo__c = true
			)
		};

		insert new TipoRecursoProduto__c(
			Produto__c =  [SELECT id FROM Product2 LIMIT 1].Id,
			TipoRecurso__c = [SELECT id FROM TiposRecurso__c LIMIT 1].Id
		);
	}

	@IsTest
	static void getBaseObjectTest() {
		Quote currentQuote = getQuote();

		ProductScreenController.getBaseObject(currentQuote.Id);
	}

	@IsTest
	static void getCheckoutDataTest() {
		Quote currentQuote = getQuote();
		ProductScreenController.getCheckoutData(currentQuote.Id);

		Opportunity currentOpportunity = getOpportunity();
		ProductScreenController.getCheckoutData(currentOpportunity.Id);
	}

	@IsTest
	static void getDataTest() {
		Quote currentQuote = getQuote();
		EstruturaProduto__c currentStructure = getStructure();

		ProductScreenController.getProducts(currentQuote.Id, currentStructure.Id, '', new List<String>{'01', '03'}, 10);
		ProductScreenController.getProducts(currentQuote.Id, null, '', new List<String>{'02', '04'}, 10);

		ProductScreenController.getStructures();

		ProductScreenController.getResources(currentStructure.Id);
	}

	@IsTest
	static void productScreenController() {
		try{CreateStructureResourcesController.getCurrentRecordsSteris(new List<CreateStructureResourcesController.ProductResourceData>{new CreateStructureResourcesController.ProductResourceData(true)});}catch(Exception ex){}
		try{CreateAcessoryResourcesController.getCurrentRecordsSteris(new CreateAcessoryResourcesController.AllAcessoryData(true));}catch(Exception ex){}
		try{CreateAcessoryResourcesController.createRecords(JSON.serialize(new CreateAcessoryResourcesController.AllAcessoryData(true)));}catch(Exception ex){}
	}

	@IsTest
	static void openQuotePDFController() {
		OpenQuotePDFController.getURL(getQuote().Id);
	}

	@IsTest
	static void openPDFController() {
		try{
			ApexPages.currentPage().getParameters().put('Id', [SELECT id FROM Quote LIMIT 1].Id);
			Test.startTest();
			PDFQuoteController pdfs = new PDFQuoteController();
			Test.stopTest();
		}catch(Exception ex){

		}
		try{
			PDFQuoteController.createPDF('', getQuote().Id, '1212');
		}catch(Exception ex){

		}

	}

	@IsTest
	static void checkNextTypeResourcesTest() {
		EstruturaProduto__c currentStructure = getStructure();

		ProductScreenController.checkNextTypeResources(currentStructure.Id, 2, new List<String>{'01', '03'});
		ProductScreenController.checkNextTypeResources(currentStructure.Id, 1, new List<String>{'02', '04'});
	}

	@IsTest
	static void saveLineItemsTest() {
		Quote currentQuote = getQuote();
		Product2 currentProduct = getProduct();
		List<ProductScreenModel.ProductData> quoteItemList = new List<ProductScreenModel.ProductData>();
		ProductScreenModel.ProductData productData = new ProductScreenModel.ProductData(currentProduct);
		ProductScreenModel.ProductData emptyProductData = new ProductScreenModel.ProductData();

		productData.price = 90;
		productData.quantity = 5;

		quoteItemList.add(productData);

		ProductScreenController.saveLineItems(currentQuote.Id, quoteItemList);
		ProductScreenController.saveLineItems(currentQuote.Id, quoteItemList);

		quoteItemList[0].id = null;
		ProductScreenController.saveLineItems(currentQuote.Id, quoteItemList);
		ProductScreenController.saveLineItems(null, quoteItemList);
	}

	static Product2 getProduct() {
		Product2 currentProduct;

		for (Product2 retrievedProduct : [
			SELECT Id,
				   Name,
				   ExternalId__c,
				   Imagem_URL__c,
				   EstruturaProduto__c,
				   KitAcessorios__c,
				   ProductCodeExternalId__c,
				   ProductCode
			  FROM Product2
			 LIMIT 1
		]) {
			currentProduct = retrievedProduct;
		}

		return currentProduct;
	}

	static EstruturaProduto__c getStructure() {
		EstruturaProduto__c currentStructure;

		for (EstruturaProduto__c retrievedStructure : [
			SELECT Id
			  FROM EstruturaProduto__c
			 LIMIT 1
		]) {
			currentStructure = retrievedStructure;
		}

		return currentStructure;
	}

	static Quote getQuote() {
		Quote currentQuote;

		for (Quote retrievedQuote : [
			SELECT Id
			  FROM Quote
			 LIMIT 1
		]) {
			currentQuote = retrievedQuote;
		}

		return currentQuote;
	}

	static Opportunity getOpportunity() {
		Opportunity currentOpportunity;

		for (Opportunity retrievedOpportunity : [
			SELECT Id
			  FROM Opportunity
			 LIMIT 1
		]) {
			currentOpportunity = retrievedOpportunity;
		}

		return currentOpportunity;
	}
}